//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parfumer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Order_elem = new HashSet<Order_elem>();
        }
    
        public int Id_order { get; set; }
        public Nullable<int> Id_user { get; set; }
        public int Id_point { get; set; }
        public int Id_status { get; set; }
        public int code { get; set; }
        public System.DateTime date { get; set; }
        public System.DateTime delivery { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_elem> Order_elem { get; set; }
        public virtual Poin_of_issie Poin_of_issie { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
    }
}
